insert into Groups (Name) values ('Vagney');
insert into Groups (Name) values ('Machado');
insert into Groups (Name) values ('Belica');
insert into Groups (Name) values ('Jhang Sadr');
insert into Groups (Name) values ('Xuân Trường');
insert into Groups (Name) values ('Yuewan');
insert into Groups (Name) values ('Mawang');
insert into Groups (Name) values ('Verkhn’odniprovs’k');
insert into Groups (Name) values ('Áno Kopanákion');
insert into Groups (Name) values ( 'Chekmagush');
insert into Groups (Name) values ( 'Dayou');
insert into Groups (Name) values ( 'Sanfang');
insert into Groups (Name) values ( 'Pingle');
insert into Groups (Name) values ( 'Marulanda');
insert into Groups (Name) values ( 'San Rafael');
insert into Groups (Name) values ( 'Cruz del Eje');
insert into Groups (Name) values ( 'Huoxian');
insert into Groups (Name) values ( 'Sukamulia');
insert into Groups (Name) values ( 'Solkan');
insert into Groups (Name) values ( 'Palampal');
