insert into GroupRoles (Name) values ('Ketotifen');
insert into GroupRoles (Name) values ('Asorbic Acid, Vitamin A Palmitate, Cholecalciferol, Thiamine Hydrochloride, Riboflavin-5 phosphate sodium, Pyridoxine Hydrochloride, Niacinamide, Dexpanthenol, Alpha-tocopherol acetate, Vitamin K1, Folic Acid, Biotin, Cyanocobalamin');
insert into GroupRoles (Name) values ('ZIKS ARTHRITIS PAIN RELIEF');
insert into GroupRoles (Name) values ('Mineral oil and white petrolatum');
insert into GroupRoles (Name) values ('atenolol');
insert into GroupRoles (Name) values ('fludrocortisone acetate');
insert into GroupRoles (Name) values ('Menthol and Camphor (Synthetic)');
insert into GroupRoles (Name) values ('Echinacea (Angustifolia), Tabebuia impetiginosa, Abies nigra, Lycopodium clavatum, Nux vomica, Phosphorus, Pulsatilla (Vulgaris), Sepia, Skatolum, Canadida albicans,');
insert into GroupRoles (Name) values ('SODIUM CHLORIDE');
insert into GroupRoles (Name) values ( 'BUMETANIDE');
insert into GroupRoles (Name) values ( 'Ethyl Alcohol');
insert into GroupRoles (Name) values ( 'Zinc Oxide and Octinoxate');
insert into GroupRoles (Name) values ( 'Doxylamine succinate');
insert into GroupRoles (Name) values ( 'methylphenidate hydrochloride');
insert into GroupRoles (Name) values ( 'citalopram');
insert into GroupRoles (Name) values ( 'Box Elder Ash Leaf Maple');
insert into GroupRoles (Name) values ( 'Bupropion Hydrochloride');
insert into GroupRoles (Name) values ( 'Carvedilol');
insert into GroupRoles (Name) values ( 'Cetirizine HCl, Pseudoephedrine HCl');
insert into GroupRoles (Name) values ( 'methscopolamine bromide');
