insert into SpendingCategories ( Name, Color) values ( 'Sachet', 'Aquamarine');
insert into SpendingCategories ( Name, Color) values ( 'Ice Cream - Fudge Bars', 'Maroon');
insert into SpendingCategories ( Name, Color) values ( 'Wine - Casillero Deldiablo', 'Pink');
insert into SpendingCategories ( Name, Color) values ( 'Strawberries', 'Pink');
insert into SpendingCategories ( Name, Color) values ( 'Sauce - Hollandaise', 'Blue');
insert into SpendingCategories ( Name, Color) values ( 'Napkin White - Starched', 'Crimson');
insert into SpendingCategories ( Name, Color) values ( 'Olives - Black, Pitted', 'Khaki');
insert into SpendingCategories ( Name, Color) values ( 'Pasta - Bauletti, Chicken White', 'Purple');
insert into SpendingCategories ( Name, Color) values ( 'Bay Leaf', 'Pink');
insert into SpendingCategories ( Name, Color) values ( 'Bar Special K', 'Orange');
insert into SpendingCategories ( Name, Color) values ( 'Soap - Pine Sol Floor Cleaner', 'Blue');
insert into SpendingCategories ( Name, Color) values ( 'Chocolate - Milk', 'Crimson');
insert into SpendingCategories ( Name, Color) values ( 'Pate - Liver', 'Violet');
insert into SpendingCategories ( Name, Color) values ( 'Squash - Guords', 'Purple');
insert into SpendingCategories ( Name, Color) values ( 'Nantucket Cranberry Juice', 'Red');
insert into SpendingCategories ( Name, Color) values ( 'Blueberries', 'Pink');
insert into SpendingCategories ( Name, Color) values ( 'Bacardi Breezer - Strawberry', 'Crimson');
insert into SpendingCategories ( Name, Color) values ( 'Hot Chocolate - Individual', 'Orange');
insert into SpendingCategories ( Name, Color) values ( 'Fiddlehead - Frozen', 'Red');
insert into SpendingCategories ( Name, Color) values ( 'The Pop Shoppe - Lime Rickey', 'Puce');
